 const columnName = ["Task ID", "Task Name", "Status", "Assignee", "Priority", "Epic", "User Story", "Sprint", "Complexity", "Dependent Resources", "Estimated Effort(in-Hours)", "Actual Time Spend", "Start Date", "End Date", "Description", "Created At", "Created By", "Updated At", "Updated By"]



const rowData = [{"Task ID":"SLC-1", "Task Name": "When either of task or bug is assigned to resources from any resources", "Status":"To-Do", "Assignee":"User-1", "Priority":"Highest", "Epic": "", "User Story": "", "Sprint":"Sprint-1", "Complexity":"High", "Dependent Resources": "Tushar", "Estimated Efforts(in-Hours)":0, "Actual Time Spend":1, "Start Date": "16-june-2021", "End Date": "1-Dec-2021", "Description":"For Project Task, Prefix should be #1", "Created At":"16-june-2021", "Created By": "Tushar", "Updated At":"16-june-2021","Updated By":"Tushar Sharma" },
{"Task ID":"SLC-2", "Task Name": "When either of task or bug is assigned to resources from any resources", "Status":"Dev Done", "Assignee":"User-2", "Priority":"High", "Epic": "", "User Story": "", "Sprint":"Sprint-1", "Complexity":"High", "Dependent Resources": "Tushar", "Estimated Efforts(in-Hours)":0, "Actual Time Spend":1, "Start Date": "16-june-2021", "End Date": "1-Dec-2021", "Description":"For Project Task, Prefix should be #1", "Created At":"16-june-2021", "Created By": "Tushar", "Updated At":"16-june-2021","Updated By":"Rishu Sharma" },
{"Task ID":"SLC-3", "Task Name": "When either of task or bug is assigned to resources from any resources", "Status":"Dev Done", "Assignee":"User-3", "Priority":"Highest", "Epic": "", "User Story": "", "Sprint":"Sprint-1", "Complexity":"High", "Dependent Resources": "Tushar", "Estimated Efforts(in-Hours)":0, "Actual Time Spend":1, "Start Date": "16-june-2021", "End Date": "1-Dec-2021", "Description":"For Project Task, Prefix should be #1", "Created At":"16-june-2021", "Created By": "Tushar", "Updated At":"16-june-2021","Updated By":"Tushar Sharma" },
{"Task ID":"SLC-4", "Task Name": "When either of task or bug is assigned to resources from any resources", "Status":"To-Do", "Assignee":"User-4", "Priority":"High", "Epic": "", "User Story": "", "Sprint":"Sprint-1", "Complexity":"High", "Dependent Resources": "Tushar", "Estimated Efforts(in-Hours)":0, "Actual Time Spend":1, "Start Date": "16-june-2021", "End Date": "1-Dec-2021", "Description":"For Project Task, Prefix should be #1", "Created At":"16-june-2021", "Created By": "Tushar", "Updated At":"16-june-2021","Updated By":"Tushar Sharma" },
{"Task ID":"SLC-5", "Task Name": "When either of task or bug is assigned to resources from any resources", "Status":"Dev Done", "Assignee":"User-5", "Priority":"Low", "Epic": "", "User Story": "", "Sprint":"Sprint-1", "Complexity":"High", "Dependent Resources": "Tushar", "Estimated Efforts(in-Hours)":0, "Actual Time Spend":1, "Start Date": "16-june-2021", "End Date": "1-Dec-2021", "Description":"For Project Task, Prefix should be #1", "Created At":"16-june-2021", "Created By": "Tushar", "Updated At":"16-june-2021","Updated By":"Tushar Sharma" }  ]

export {rowData}
export {columnName}